// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqbr4D3b-Sc-HtSw8Hn5gIa1sGegl9kVo',
    appId: '1:219637772331:web:823c216ec3dbe9fee93a6e',
    messagingSenderId: '219637772331',
    projectId: 'chatapp-21bb8',
    authDomain: 'chatapp-21bb8.firebaseapp.com',
    storageBucket: 'chatapp-21bb8.appspot.com',
    measurementId: 'G-WB8MHPF194',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlqWVT4YGp4UPz0SCGlqU-hNT2on-QB6w',
    appId: '1:219637772331:android:7e65606d9e06cd94e93a6e',
    messagingSenderId: '219637772331',
    projectId: 'chatapp-21bb8',
    storageBucket: 'chatapp-21bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eEEbHU1phcO6y7UCjXK_32QPiV_9DRs',
    appId: '1:219637772331:ios:ff9ce8241f686faae93a6e',
    messagingSenderId: '219637772331',
    projectId: 'chatapp-21bb8',
    storageBucket: 'chatapp-21bb8.appspot.com',
    iosClientId: '219637772331-qo9oivfa8m1hopam7inidmb0e99r1dub.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3eEEbHU1phcO6y7UCjXK_32QPiV_9DRs',
    appId: '1:219637772331:ios:5a3b3406d6297508e93a6e',
    messagingSenderId: '219637772331',
    projectId: 'chatapp-21bb8',
    storageBucket: 'chatapp-21bb8.appspot.com',
    iosClientId: '219637772331-nbg4qgptgdc71p2oce30rahirmnullc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppReal.RunnerTests',
  );
}
